module AbsFragments where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data Grammar =
   Grammar [Def]
  deriving (Eq,Ord,Show)

data Def =
   Rule [Fragment]
  deriving (Eq,Ord,Show)

data Fragment =
   Fragment [Item]
  deriving (Eq,Ord,Show)

data Item =
   Terminal Ident
 | NonTerminal Ident
  deriving (Eq,Ord,Show)

