#ABNF 1.0 UTF-8;
meta "grammar format" is "test";
root $Statement;

$Statement = ABNF grammars are so cool
           | $a 
           | $Utterance_1 ;

$a = b 
   | $Individual_2 [new york]
   | [hello | huhu] world 
   | a (b | $c and $d | rock'n'roll) ;

public $Individual_2 = don't | don't | don't ;

$c = $NULL | $A2 | $A3 | $A4 ;

$Statement_18 = [depart | leave] | [go] ;

$Utterance_1 = do you have $Unknown_1
               | (list | (give | show) me) $Unknown_1 ;

$nestedItems = (i1 | (i2 | i3)) ;

$A1 = $B | $B | $B ;
$A2 = $B | $B | $B ;
$A3 = $B | $B ;

