module AbsABNF where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data Grammar =
   Grammar [Def]
  deriving (Eq,Ord,Show)

data Def =
   Header
 | Root Var
 | Rule LHS [Fragment]
  deriving (Eq,Ord,Show)

data LHS =
   Internal Var
 | Public Var
  deriving (Eq,Ord,Show)

data Fragment =
   Fragment [Item]
  deriving (Eq,Ord,Show)

data Item =
   Terminal Ident
 | NonTerminal Var
 | Option [Choice]
 | Group [Choice]
  deriving (Eq,Ord,Show)

data Choice =
   Choice [Item]
  deriving (Eq,Ord,Show)

data Var =
   Var Ident
  deriving (Eq,Ord,Show)

